### ISSUE TITLE
Template's default project name is too long

### ISSUE THREAD

**Issue by ExtendVS** [AlexanderViken/alexanderviken#2]
![attachfilehandler](https://cloud.githubusercontent.com/assets/10539287/8317369/c1e9d270-19b1-11e5-8c17-f2a21c24b7eb.png)

**Comment by AlexanderViken** [comment]
There is a new version out that tries to mitigate this issue. The root cause is the limitation in Windows that prevents paths longer than 252 chars. Please try with the new and updated version.
